name: Test MikroTik VPN Management System

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Check shell scripts syntax
      run: |
        echo "Checking shell script syntax..."
        for script in *.sh; do
          if [ -f "$script" ]; then
            echo "Checking $script..."
            shellcheck "$script" || echo "Warning: Issues found in $script"
          fi
        done
    
    - name: Validate file permissions
      run: |
        echo "Checking file permissions..."
        ls -la *.sh
        for script in *.sh; do
          if [ -f "$script" ]; then
            if [ -x "$script" ]; then
              echo "✓ $script is executable"
            else
              echo "✗ $script is not executable"
            fi
          fi
        done
    
    - name: Check required files
      run: |
        echo "Checking required project files..."
        required_files=("README.md" "install.sh" "vps_setup.sh" "menu.sh" "mikrotik_config_generator.sh")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✓ $file found"
          else
            echo "✗ $file missing"
            exit 1
          fi
        done
    
    - name: Validate README
      run: |
        echo "Checking README.md..."
        if [ -s README.md ]; then
          echo "✓ README.md is not empty"
        else
          echo "✗ README.md is empty"
          exit 1
        fi 